### ISSUE TITLE
Make ban messages more detailed.

### ISSUE THREAD

**Issue by KaloHG** [CivClassic/BanStick#21]
In a fatal rail accident... once upon a time... ok lets skip the story.

Currently ban messages are simply, "Administrative Ban". The only message you get is if you are in-game when you are banned, at which point it will say for a split second "You have been banned, reason: time: etc:" then you get banned.

This isn't really descriptive at all, and I feel like it would be a very good QOL improvement to have a ban time (if applicable) and ban reason (if reason provided) as well as a nice little "modmail on /r/civclassics" tick.

What ban messages look like now: https://i.imgur.com/cn89vQL.png

**Comment by wingzero54** [comment]
These are already features of banstick

**Comment by KaloHG** [comment]
Then why aren't they implemented, are people just not providing reasons on bans???

As well as if the ban is temporary, it still doesn't show when you'll be unbanned. I know from personal experience :(

I don't think people should have to go on a witch hunt to harass the admins to find out why they're banned/when they get unbanned.

**Comment by wingzero54** [comment]
Seeing as we do have ban messages, admins are just too lazy to type them in, I think it's safely outside the purview of code
