### ISSUE TITLE
Allow vpn banned players to login without vpn

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/BanStick#23]
Currently if a player is suspected to have a VPN enabled they are banned. If they turn the VPN off and try to login again, they cannot because they've been banned. If a player is banned for VPN there should be something that checks if they are still using a VPN when they subsequently attempt to login so manual involvement isn't required every time.

**Comment by Protonull** [comment]
This would unfortunately lead to the situation of people testing different VPNs to see what is and isn't caught by BanStick.

**Comment by wingzero54** [comment]
Oh damn you're absolutely right. FML
