### ISSUE TITLE
Automatically print lovetap on new player join

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/BanStick#6]
Should be toggleable via config setting. I want this so I can have Kira suck it up and give it to me.

**Comment by MrXFier** [comment]
Sounds like a way to punish the vast majority of innocent players. Bad idea max!

**Comment by Maxopoly** [comment]
Implemented in https://github.com/CivClassic/BanStick/commit/c6c3663882f57b26cfcf101e0a2a5a2f5a275f2a
