### ISSUE TITLE
Add command to forgive registrar

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/BanStick#9]
Having to manually delete them from the db is not ideal

**Comment by MrXFier** [comment]
This is a good one, but we should be forgiving every IP. People are more security orientated these days and it is an assault on liberty to ban VPNs, bad apples be damned.

**Comment by Maxopoly** [comment]
Implemented in https://github.com/CivClassic/BanStick/commit/c6c3663882f57b26cfcf101e0a2a5a2f5a275f2a
